apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: pr0mise-ambulance-ufe-content
spec:
  microFrontend: pr0mise-ambulance-ufe
  element: pr0mise-ambulance-wl-app
  attributes:
  - name: api-base
    value: http://localhost:5000/api
  - name: ambulance-id
    value: bobulova
  - name: base-path
    value: /pr0mise-ambulance-wl/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?pr0mise-ambulance-wl(/.*)?$"